version: '3.8'

services:

  app:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: byme_fixit
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
<<<<<<< HEAD
      - "3306:3306"
=======
      - "3306:3306"
>>>>>>> 6ccc0eff8db2a7438a79a53ddccc2cc9609c6ad8
